[build]
  command = "npm run build"
  publish = "dist"

# Leitet alle API-Calls an deinen lokalen/ngrok-Server weiter
[[redirects]]
  from = "/api/*"
  to = "https://DEINE-NGROK-URL/:splat"
  status = 200
  force = true

# SPA-Fallback (damit deine React-Routen wie /reports nicht 404 geben)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200